[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_multisig = "5Lvr9CwXgUHXrNnwBnGzENSYbxvhgjVT4kF8bKgnhQxv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/mathias/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
